version: '3.8'

services:
  mysql:
    image: mysql:8.4
    container_name: mysql
    environment:
      MYSQL_DATABASE: vehicle_db
      MYSQL_ROOT_PASSWORD: 03012002
      MYSQL_USER: appuser
      MYSQL_PASSWORD: apppass
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d
    networks:
      - vehicle-net
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "mysql", "-uroot", "-p03012002"]
      interval: 5s
      timeout: 10s
      retries: 15

  app:
    build:
      context: .
      args:
        - WAIT_FOR_IT_VERSION=master
    container_name: vehicle-app
    ports:
      - "8080:8080"
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: docker
      DB_USER: appuser
      DB_PASS: apppass
    networks:
      - vehicle-net
    command: ["./wait-for-it.sh", "mysql:3306", "--timeout=90", "--", "java", "-jar", "app.jar"]

volumes:
  mysql_data:

networks:
  vehicle-net:
    name: vehicle-network
    driver: bridge
