version: '3.8'

services:
  mysql:
    image: mysql:8
    container_name: mysql
    environment:
      MYSQL_DATABASE: vehicle_db
      MYSQL_ROOT_PASSWORD: 03012002
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - vehicle-net

  app:
    build: .
    container_name: vehicle-app
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    networks:
      - vehicle-net

volumes:
  mysql_data:

networks:
  vehicle-net:
